<a href="https://colab.research.google.com/github/JustBoyd/DataScienceFraudTask/blob/main/Credit_Card_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
97137,66085,0.998571,-0.046655,0.644378,1.114925,-0.665698,-0.627024,-0.002057,0.018110,-0.052156,...,-0.171808,-0.784227,0.095822,0.455048,0.167887,-0.729060,0.004417,0.037612,89.0,0.0
97138,66085,-1.326193,0.549467,1.220272,1.286509,0.473532,-0.681876,-0.249255,0.444731,-0.768583,...,0.088777,0.029885,-0.123943,-0.092548,-0.159851,-0.360097,0.318036,0.007246,3.6,0.0
97139,66086,1.230983,-0.224520,-0.345196,0.212802,1.586953,3.997378,-1.145351,1.068038,0.584379,...,0.067612,0.229977,-0.119921,1.019614,0.667317,-0.226637,0.071064,0.028365,1.0,0.0
97140,66086,1.241193,0.767604,-0.210715,1.297487,0.152102,-1.162435,0.389686,-0.321743,-0.288129,...,-0.036601,0.032307,-0.136263,0.308814,0.738340,-0.331821,0.040823,0.054137,1.0,0.0
97141,66087,0.310485,-2.576074,1.002015,0.011196,-2.280745,0.465648,-0.860224,0.156411,0.087629,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97142 entries, 0 to 97141
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    97142 non-null  int64
 1   V1      97142 non-null  float64
 2   V2      97142 non-null  float64
 3   V3      97142 non-null  float64
 4   V4      97142 non-null  float64
 5   V5      97142 non-null  float64
 6   V6      97142 non-null  float64
 7   V7      97142 non-null  float64
 8   V8      97142 non-null  float64
 9   V9      97142 non-null  float64
 10  V10     97142 non-null  float64
 11  V11     97142 non-null  float64
 12  V12     97142 non-null  float64
 13  V13     97142 non-null  float64
 14  V14     97142 non-null  float64
 15  V15     97142 non-null  float64
 16  V16     97142 non-null  float64
 17  V17     97142 non-null  float64
 18  V18     97142 non-null  float64
 19  V19     97141 non-null  float64
 20  V20     97141 non-null  float64
 21  V21     97141 non-null  float64
 22  V22     97141 non-null  float64
 23  V23     97141 non-null  float64
 24  V24     97141 non-null  float64
 25  V25     97141 non-null  float64
 26  V26     97141 non-null  float64
 27  V27     97141 non-null  float64
 28  V28     97141 non-null  float64
 29  Amount  97141 non-null  float64
 30  Class   97141 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 23.0 MB

In [6]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [7]:
credit_card_data['Class'].value_counts()

0.0    96919
1.0      222
Name: Class, dtype: int64

In [9]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(96919, 31)
(222, 31)

In [11]:
legit.Amount.describe()

count    96919.000000
mean        98.310270
std        265.983851
min          0.000000
25%          7.580000
50%         26.610000
75%         89.345000
max      19656.530000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     222.000000
mean      114.488243
std       255.373074
min         0.000000
25%         1.000000
50%         7.805000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [14]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,41730.096658,-0.249732,-0.043534,0.694778,0.151455,-0.269573,0.098435,-0.093862,0.050744,-0.036243,...,0.043675,-0.031999,-0.108137,-0.036618,0.009741,0.131925,0.026549,-0.000700,0.001378,98.310270
1.0,36541.941441,-6.044462,4.134072,-7.932926,4.915738,-4.386432,-1.796113,-6.300490,2.722455,-2.896811,...,0.345305,0.715188,-0.125165,-0.265450,-0.105791,0.205945,0.103589,0.523395,0.037908,114.488243

In [17]:
legit_sample = legit.sample(n=222)

In [18]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [19]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2476,2039,-0.642456,0.360573,1.191212,0.364345,0.946524,-0.266670,0.072068,0.231482,-0.764055,...,-0.057728,-0.337859,0.134496,-0.352322,-0.776601,0.121268,0.128574,0.168394,1.98,0.0
90647,63103,-1.954504,-0.739505,2.303758,3.467926,-0.643549,0.067393,-0.862886,0.846507,-0.964231,...,0.665984,1.043384,0.400636,0.595268,-0.679933,0.280028,0.058953,-0.101881,173.25,0.0
29048,35295,0.039490,-0.715862,2.432075,-1.729158,-1.609506,-0.172390,-0.645934,-0.127354,-1.470741,...,-0.211270,0.079883,-0.054117,0.379427,-0.198717,-0.264513,-0.064949,-0.184302,29.90,0.0
22953,32518,-0.365265,0.815640,-1.601097,-0.168861,2.866318,2.985511,0.203255,0.907551,-0.586788,...,0.067789,0.341991,0.252022,0.999715,-0.503678,-0.427616,0.055673,-0.094098,3.98,0.0
42800,41251,-0.039566,-2.318770,0.041215,0.689345,-1.123152,0.922330,0.109388,0.249319,0.691877,...,0.421028,0.176142,-0.572587,-0.158064,0.066876,1.150055,-0.138144,0.087447,599.71,0.0

In [20]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
95534,65358,1.193916,-0.571085,0.742522,-0.014588,-0.624561,0.832162,-0.833350,0.272897,1.169425,...,-0.049502,0.207265,-0.265272,-0.679294,0.511812,1.246604,-0.028671,-0.006112,31.91,1.0
95597,65385,-2.923827,1.524837,-3.018758,3.289291,-5.755542,2.218276,-0.509995,-3.569444,-1.016592,...,-0.511657,-0.122724,-4.288639,0.563797,-0.949451,-0.204532,1.510206,-0.324706,1354.25,1.0
96341,65728,1.227614,-0.668974,-0.271785,-0.589440,-0.604795,-0.350285,-0.486365,-0.010809,-0.794944,...,-0.026055,-0.295255,-0.180459,-0.436539,0.494649,-0.283738,-0.001128,0.035075,98.01,1.0
96789,65936,-3.593476,0.781442,-1.822448,0.605761,-1.194656,-0.517195,-1.722523,0.128890,0.014963,...,0.351792,0.391249,-0.252875,-0.498042,0.010172,0.909929,-1.478767,0.722673,101.50,1.0
96994,66037,0.286302,1.399345,-1.682503,3.864377,-1.185373,-0.341732,-2.539380,0.768378,-1.547882,...,0.352456,-0.243678,-0.194079,-0.172201,0.742237,0.127790,0.569731,0.291206,7.53,1.0

In [21]:
new_dataset['Class'].value_counts()

0.0    222
1.0    222
Name: Class, dtype: int64

In [22]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,41645.481982,-0.120163,-0.016535,0.621645,0.129396,-0.159835,0.069226,-0.084325,-0.031856,-0.071387,...,0.104738,-0.126413,-0.137604,-0.055335,-0.064971,0.122548,0.039780,-0.030468,-0.013312,92.719189
1.0,36541.941441,-6.044462,4.134072,-7.932926,4.915738,-4.386432,-1.796113,-6.300490,2.722455,-2.896811,...,0.345305,0.715188,-0.125165,-0.265450,-0.105791,0.205945,0.103589,0.523395,0.037908,114.488243

In [23]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [24]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
2476    2039 -0.642456  0.360573  1.191212  0.364345  0.946524 -0.266670
90647  63103 -1.954504 -0.739505  2.303758  3.467926 -0.643549  0.067393
29048  35295  0.039490 -0.715862  2.432075 -1.729158 -1.609506 -0.172390
22953  32518 -0.365265  0.815640 -1.601097 -0.168861  2.866318  2.985511
42800  41251 -0.039566 -2.318770  0.041215  0.689345 -1.123152  0.922330
...      ...       ...       ...       ...       ...       ...       ...
95534  65358  1.193916 -0.571085  0.742522 -0.014588 -0.624561  0.832162
95597  65385 -2.923827  1.524837 -3.018758  3.289291 -5.755542  2.218276
96341  65728  1.227614 -0.668974 -0.271785 -0.589440 -0.604795 -0.350285
96789  65936 -3.593476  0.781442 -1.822448  0.605761 -1.194656 -0.517195
96994  66037  0.286302  1.399345 -1.682503  3.864377 -1.185373 -0.341732

             V7        V8        V9  ...       V20       V21       V22  \
2476   0.072068  0.231482 -0.764055  ...  0.171948 -0.057728 -0.337859
90647 -0.862886  0.846507 -0.964231  ...  0.719428  0.665984  1.043384
29048 -0.645934 -0.127354 -1.470741  ... -0.168162 -0.211270  0.079883
22953  0.203255  0.907551 -0.586788  ...  0.071650  0.067789  0.341991
42800  0.109388  0.249319  0.691877  ...  1.024181  0.421028  0.176142
...         ...       ...       ...  ...       ...       ...       ...
95534 -0.833350  0.272897  1.169425  ...  0.062908 -0.049502  0.207265
95597 -0.509995 -3.569444 -1.016592  ... -0.447039 -0.511657 -0.122724
96341 -0.486365 -0.010809 -0.794944  ...  0.273799 -0.026055 -0.295255
96789 -1.722523  0.128890  0.014963  ... -0.478219  0.351792  0.391249
96994 -2.539380  0.768378 -1.547882  ...  0.270360  0.352456 -0.243678

            V23       V24       V25       V26       V27       V28   Amount
2476   0.134496 -0.352322 -0.776601  0.121268  0.128574  0.168394     1.98
90647  0.400636  0.595268 -0.679933  0.280028  0.058953 -0.101881   173.25
29048 -0.054117  0.379427 -0.198717 -0.264513 -0.064949 -0.184302    29.90
22953  0.252022  0.999715 -0.503678 -0.427616  0.055673 -0.094098     3.98
42800 -0.572587 -0.158064  0.066876  1.150055 -0.138144  0.087447   599.71
...         ...       ...       ...       ...       ...       ...      ...
95534 -0.265272 -0.679294  0.511812  1.246604 -0.028671 -0.006112    31.91
95597 -4.288639  0.563797 -0.949451 -0.204532  1.510206 -0.324706  1354.25
96341 -0.180459 -0.436539  0.494649 -0.283738 -0.001128  0.035075    98.01
96789 -0.252875 -0.498042  0.010172  0.909929 -1.478767  0.722673   101.50
96994 -0.194079 -0.172201  0.742237  0.127790  0.569731  0.291206     7.53

[444 rows x 30 columns]

In [26]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [27]:
print(X.shape, X_train.shape, X_test.shape)

(444, 30) (355, 30) (89, 30)

In [28]:
model = LogisticRegression()

In [30]:
model.fit(X_train, Y_train)

LogisticRegression()

In [31]:
X_train_prediction = model.predict(X_train)
training_data_accuracy= accuracy_score(X_train_prediction, Y_train)

In [32]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9633802816901409

In [33]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [34]:
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.9101123595505618